### ISSUE TITLE
add fields: continent, region, etc.

### ISSUE THREAD

**Issue by PeterTheOne** [Pirate-Parties-International/PPI-party-info#11]
* continent so that you can filter by continent.
* region: there are some regional parties that only belong to one region. additionally there should be a field that says if it's a regional party or a country wide party.
* Astronomical object / planet
* City/Coordinates of headquarter

**Comment by Putr** [comment]
Continent is not required as we know where countries are located.

Region - adding now for regional parties.

Astronomical object/planet - lol :) Planet 9 it is!

City/Coordinates of headquarters - sounds good.

**Comment by PeterTheOne** [comment]
thnx :)

**Comment by Croydon** [comment]
Excellent. I will wait for the planet values. 
Made my day :laughing:
