### ISSUE TITLE
Verify data

### ISSUE THREAD

**Issue by Putr** [Pirate-Parties-International/PPI-party-info#17]
So, the data is pretty old so it needs to be verified.

- Defunct parties should be removed
- URLs should be checked & updated
- Contacts should be updated

- Membership in PPEU and PPI should be checked (it was migrated automatically, observer members are logged incorrectly)

**Comment by PeterTheOne** [comment]
- [ ] PPAR
- [ ] PPAT
- [ ] PPAU
- [ ] PPBA
...

**Comment by collentine** [comment]
thanks. Will try to get it verified this week.

**Comment by Airon90** [comment]
I think we should not remove defunct parties but keep track of them. We could create a boolean data "defunct" or we can keep timestap of founding date and ceasing date.

**Comment by Putr** [comment]
"Established" date would be interesting in it's own right, but this presents a problem what this date is: date when group first started organizing or when they got officially registered?

With ceasing date we have the problem of parties that reactivate.

I think the simplest solution would be "active: true|false". When we don't hear from them for a while we set it to false. When they complain, we set it to true ;).
This can enable us to add a simple message "This party seems to not be active. Consider restarting it?". This may help with the situation where people interested in pirate party movement get demotivated by the inactivity of their local party.

**Comment by Airon90** [comment]
IMHO established date is the date when the party got officially registered as the party is officially recognized from that date on.

Both established date and ceasing date could be an array: when a party will reactivate, "established date" variable will have two dates and "ceasing date" one. If the party ceases again its activities, then both variables will have two dates. And so on.

Boolean "active" IMHO is not a good solution, as a party can be active (e.g. accepting memberships, talking about party, ...) but not working (e.g. participate to elections, to public events, not updating its communication channels, ...)

**Comment by Putr** [comment]
The "established" than has a problem with parties in countries like Russia - huge active parties .. that just can't get registered due to getting blocked by the government. As far as I'm concerned a party is a party regardless of it's relationship to the state.

Active/ceasing array has the problem that most of these dates will not be official and it'll be hard to convey any meaningful information. Especially since the inactive or sporadically active parties are the ones we know very little about.

The boolean active switch (maybe a better name: "currentlyActive") could communicate if the moderators of this dataset have detected meaningful activity - are the "owners" of the party even interested in running it. 

I think this peace of information is very interesting to:

(a) people from those countries who have just found out about the pirate movement and would like to join their local branch [in this case a non-functioning but active party, that's working on becoming functioning, is a lot different than a few people sitting on a domain name and not responding to new activists] 

(b) other pirate parties - as long as they are active we can help them become functioning or at least cooperate with them because they are actively responding to us.

**Comment by collentine** [comment]
A boolean switch sounds like a great option. Maybe also add a display
option to website based on this to show only active parties.

When I compiled data my method of determining if a country was active was
in a very inclusive way. I checked if there was any activity on different
social media channels or their website in past 60(?) days. 2/3 active
channels and I considered party active. Just bringing up an example to show
how subjective and hard it can be to determine "active party" from an
outside perspective

**Comment by collentine** [comment]
Will continue tomorrow, not sitting at my own computer atm and process is too slow for checking stuff from here. Note to self: PPAR mail contact should be a mail:to rather than url to API site. Might be same on other parties that have a form as contact

**Comment by collentine** [comment]
only 9 left now, should be able to finish it tonight.

Checked PPI memberships from those that resigned recently but haven't checked PPEU. Should be easily controlled once we get a filtering so we can just compare straight on with members. We need to decide what to do with "dead" parties

**Comment by collentine** [comment]
gone through all on the list. A few not there that we need to decide upon + the ones without activity...

**Comment by Putr** [comment]
So, we've agreed in a chat to add a "defunct" switch.
