### ISSUE TITLE
Add data to Wikidata

### ISSUE THREAD

**Issue by Airon90** [Pirate-Parties-International/PPI-party-info#29]
[Wikidata](https://www.wikidata.org) is the latest project of the Wikimedia Foundation. Its aim is to create a Wikipedia of data.
It keeps tracks of many items under CC-0 licence and it has items about Pirate parties too (see [item about PPSE](https://www.wikidata.org/wiki/Q208602) or [item about PPIT](https://www.wikidata.org/wiki/Q1737170)).
Many data can be added on Wikidata. This is the code about PPIT:

- ```partyCode``` is defined by the "Also known as" in the table above
- ```countryCode``` can be read from the value on [P17](https://www.wikidata.org/wiki/P:P17)
- ```country``` is defined by [P17](https://www.wikidata.org/wiki/P:P17)
- ```partyName``` is defined by the labels in the table above. It has support for all languages. Otherwise, if ```partyName``` keeps track only of the official party name, it is defined by [P1448](https://www.wikidata.org/wiki/P:P1448)
- ```type```:
  - ```national```: it should have [Q3664326](https://www.wikidata.org/wiki/Q3664326) in [P31](https://www.wikidata.org/wiki/P:P31)
  - sincerely I don't know right now how to have support for ```regional``` and ```local``` variables
  - ```youth```: it should have [Q8059357](https://www.wikidata.org/wiki/Q8059357) in [P31](https://www.wikidata.org/wiki/P:P31). As a prove, in the parent organisation there should be [P527](https://www.wikidata.org/wiki/P:P527) defined with the item of the youth wing and [P518](https://www.wikidata.org/wiki/P:P518)  defined with [Q190007](https://www.wikidata.org/wiki/Q190007) as qualifier
- ```parentorganisation``` is defined by [P1416](https://www.wikidata.org/wiki/P:P1416). It is interesting to see the inverse, i.e. what has been created from the party (regional and local parties, other organizations, youth wing, women wing, newspaper, ...). These data are defined by [P527](https://www.wikidata.org/wiki/P:P527) with specific qualifiers 
- ```headquarters```:
  - ```coordinates``` is defined by [P625](https://www.wikidata.org/wiki/P:P625) (I don't know if it is used as standalone or as qualifier of [P625](https://www.wikidata.org/wiki/P:P625))
  - ```address``` is defined by some properties and qualifiers (properties of a statement). [P159](https://www.wikidata.org/wiki/Property:P159) defines the city where the headquarters are present. Then:
    - if the street has an item on Wikidata, the qualifiers [P670](https://www.wikidata.org/wiki/P:P670) and [P669](https://www.wikidata.org/wiki/P:P669) define respectively the street and the civic number
    - if the street doesn't have an item on Wikidata, [P969](https://www.wikidata.org/wiki/Property:P969) and [P281](https://www.wikidata.org/wiki/Property:P281) define respectively the address with the civic number and the postal address of the headquarters.
- ```websites```:
  - ```official``` is defined by  [P856](https://www.wikidata.org/wiki/P:P856) 
  - by now I think it is not possible to define ```forum```, ```liquidfeedback``` and ```wiki```
- ```socialNetworks```:
  - ```facebook```:
    - ```username``` is defined by [P2013](https://www.wikidata.org/wiki/P:P2013)
    - I don't know how to get ```id``` variable
  - ```twitter```
    - ```username``` is defined by [P2002](https://www.wikidata.org/wiki/P:P2002)
    - it is impossible to define ```hashtag``` variable (and I think it is also useless: #30)
  - if ```youtube``` variable is defined as channel ([it is not documented yet](https://github.com/Pirate-Parties-International/PPI-party-info/blob/master/doc/data_specification.md)), there is the property [P2397](https://www.wikidata.org/wiki/P:P2397)
  - ```googlePlus```, ```irc```, ```dfsn``` and so on are defined by [P553](https://www.wikidata.org/wiki/P:P553), which defines the name of the social network, and [P554](https://www.wikidata.org/wiki/P:P554), used as qualifier, which defines the ID
- ```membership```
  - ```ppi```: the item should have [Q170](https://www.wikidata.org/wiki/Q170) in [P361](https://www.wikidata.org/wiki/Property:P361) for both "full" and "observer". If it is an observer, there should be a qualifier [P794](https://www.wikidata.org/wiki/P:P794) defined with [Q818553](https://www.wikidata.org/wiki/Q818553)
  - ```ppeu```: the item should have [Q15081858](https://www.wikidata.org/wiki/Q15081858) in [P361](https://www.wikidata.org/wiki/Property:P361) for both "full" and "observer". If it is an observer, there should be a qualifier [P794](https://www.wikidata.org/wiki/P:P794) defined with [Q818553](https://www.wikidata.org/wiki/Q818553)
- ```contact``` can't be defined (by now, because I'm going to propose the creation of this property)

The advantage of using Wikidata is that data are not defined on a single project by available for everyone on a public and known platform. Moreover, and there are more data than the ones inserted (e.g. number of members, creation date, presidents, chairmen, founder, logo, political collocation, ...
The problem is that not everything by now can be easily defined.

Data from Wikidata can be retrieved easily: [Q1737170](https://www.wikidata.org/wiki/Q1737170) (PP-IT) → https://www.wikidata.org/entity/Q1737170.json

**Comment by Putr** [comment]
First, let's define the scope of this project:

To build and maintain a basic data set of information about international pirate parties and their contacts.

So, it has to:
(a) be actively maintained (by outside observers, not members of the party)
(b) satisfy a basic need to know "who to contact in japan?"

# There are several issues:

* 3rd party system *
The intention of the creation of this system was not to create an API, but to create a way for us to maintain a central, public registry of parties, that we control, but anyone can suggest edits (this is way I chose github with it's merge requests).

Display still requires a separate website even if it used wikidata.

* More Data *
We can always add more data. But it must be understood that this dataset is not meant to be "everything we know about pirate parties" because we just don't have the manpower to maintain such a dataset, plus that kind of data is not required. We just need an index of parties.

# Sync to wikidata

But there is an added benefit to syncing data to wikidata. But this is outside the scope of this project and my allotted time for this project. Sync would be quite simple to develop - if someone would like to do it I'll be happy to help.

(PS: I'm teaching a number of people coding, so I may give it to one of them as it's a good limited, well defined project)

**Comment by Airon90** [comment]
Ok, I understand that the aim of such project is to have data about Pirate parties, that can be useful to those who want to become a pirate or to have information about the party itself.
In order to be actively maintained I think that we should avoid to have so much datasets, otherwise information on some datasets can be old and people don't know which dataset shows the correct data.
That's why I propose to update some data on Wikidata, so that a greater community can keep those information up-to-date, instead of constatly have to verify data (see #17)
Some information can be taken from there and other can be left on GitHub, so that [data about PPIT](https://github.com/Pirate-Parties-International/PPI-party-info/blob/master/data/ppit.json) will become (just because I don't know why to keep ID in Facebook variable, I'm not expert about IRC and I don't know how to integrate it into Wikidata and you think that hastags are useful #30):

```
{
    "wikidata": "Q1737170",
    "socialNetworks": {
        "facebook": {
            "id": "96268424342" 
        },
        "twitter": {
            "hashtag": "#PartitoPirata"
        },
        "irc": {
            "ircChannel": "pirati",
            "ircServer": "hinezumi.im"
        },
    "contact": {
        "general": {
            "email": "info@partito-pirata.it"
        }
    }
}
```

From Wikidata, whose aim is to store "everything we know about pirate parties" in a machine readable dataset, you can extract the data you need and you can keep additional data, such as hashtags, email addresses and so on, in the original JSON files.
You don't have to sync data, you just need to extract data from another dataset.
But I know that doesn't worth to make such changes (in Italian we would say *Il gioco non vale la candela*)

**Comment by collentine** [comment]
The data points we have chosen are specifically of the type that won't
frequently change = updating won't be a heavy task

**Comment by collentine** [comment]
migrating to wikidata is outside scope of this project so closing this issue now. Feel free to migrate or find other people willing to help you. Believe having only a few dedicated people to keeping PAPI updated will show more progress than the wiki community
