### ISSUE TITLE
Removing "hashtag" variable

### ISSUE THREAD

**Issue by Airon90** [Pirate-Parties-International/PPI-party-info#30]
I think that "hashtag" variable is not useful.
A party can create as many hashtag as it wants and as it needs.
For example the staff under PPIT channel uses both "#VotoPirata" (#IvotePirate) and " #VotaPirata" (#VotePirate) and many other hashtags.
Moreover there are hashtags used for single campains that can't be always listed.

**Comment by PeterTheOne** [comment]
I think it's good to have the hastags. It doesn't have to be every hashtag for every campaign but just the main ones that are used for the party.

**Comment by Putr** [comment]
The original ideas was to add the hashtag that the party always uses, and which it's members use to tag tweets when talking about topics in relation to the party.

I personally never saw hashtags used in the pirate movement like that (except maybe #ppint) but as long as there "are some", I think it's a usefull datapoint.

**Comment by collentine** [comment]
Agree. Of course there are separate campaign hashtags and no need to keep track of them with this registry, however the more general ones stay the same and are useful.
