### ISSUE TITLE
partyName no language codes used

### ISSUE THREAD

**Issue by PeterTheOne** [Pirate-Parties-International/PPI-party-info#39]
The documentation says languages codes should be used for `partyName`. In the current dataset `en` is correct but the second code always seems to be the countryCode and not the language code.

Example:

    {
        "countryCode": "at",
        "partyName": {
            "en": "Pirate Party Austria",
            "at": "Piratenpartei \u00d6sterreich"
        },
    }

According to the doc `partyName->at` should be `partyName->de`.

For example `"ca": "Pirate Party of Canada && Parti Pirate du Canada"` looks really wrong.

If we change this according to the doc we lose the hidden feature that we can select the official partyName by using the countryCode to select the correct name. So I'm not sure how to solve this.

**Comment by collentine** [comment]
I believe the benefits are more important than being correct in this situation. 

How about changing the doc to something similar to:
the partyName is written in two versions. Primarily the English translation that is denoted as "en" and standardized to be Pirate Party 'Country'. The second part is the native and correct name of the party denoted by the country's code. 

However this is still a bit strange for countries with several languages e.g. Belgium. Thus I'm still not sure how to solve this.

**Comment by collentine** [comment]
An alternative would be specifying those countries with several party names combined under country name and then separated into each language. e.g.
PPBE
"en": Pirate Party Belgium
"be": "Parti Pirate && Piraten Partij && Piraten Partei"
"nl": "Piraten Partij"
"fr": "Parti Pirate"
"de": "Piraten Partei"

Believe this might be complicating manner too much though so maybe we should just add countrycode and remove rest?

**Comment by PeterTheOne** [comment]
My main concern is that the documentation matches what really happens.

Secondly it would be nice to have Englisch and the Official name (or names?) somehow. But I'm not sure how the parties handle it. Is their official name the combined `Pirate Party of Canada && Parti Pirate du Canada` or do they have two official names as in `Pirate Party of Canada` and `Parti Pirate du Canada`.

> An alternative would be specifying those countries with several party names combined under country name and then separated into each language.

I like your idea. we could also use `"official"` instead of the country code.

**Comment by collentine** [comment]
believe each country treats this differently and thus each party as well.
e.g. Swedish only became official language in Sweden in 2009...



*Other contact:*
Skype: josef.ohlsson.collentine
Blog:    http://blog.collentine.com
Twitter: @collentine

**Comment by Fafrin** [comment]
For names, we should use language names, not country names.
-> we need "party language". If not provided, country code is used, if not present, en is used.

**Comment by PeterTheOne** [comment]
There could be multiple party languages..

**Comment by Fafrin** [comment]
But there certainly is one in whitch the party preferes its name to be displayed here.

**Comment by Putr** [comment]
The documentations says it's a language, because that's why we even have a multi value there. This was developed to support countries with multiple official languages and thus multiple official names. If we just wanted to use englishName and officialName it would be simpler to just use to separate fields.

So yes, @PeterTheOne your example for PPAT is indeed an error in the dataset - that should be a "de".

PS: Some entries still use the "&&" concatenated notation - this should be refactored.

**Comment by PeterTheOne** [comment]
> So yes, @PeterTheOne your example for PPAT is indeed an error in the dataset - that should be a "de".

Ok, but this is not only the case for PPAT a lot of parties have it wrong..

**Comment by collentine** [comment]
I'll look through it

**Comment by Putr** [comment]
Thanks!

**Comment by collentine** [comment]
corrected language codes. Choose to simplify when possible. e.g. not brazilian-portugues - just portuguese. Followed the ISO 639-2 Code for languages https://www.loc.gov/standards/iso639-2/php/code_list.php

Did not see any "&&" concatenated notations to correct. 

Found a faulty countrycode for PPJP so corrected that as well.
