### ISSUE TITLE
Young party names

### ISSUE THREAD

**Issue by PeterTheOne** [Pirate-Parties-International/PPI-party-info#46]
How should the youth party file name and partycode look like? Please specify in the doc.

There is a pullrequest with `YPCZ`.

**Comment by Fafrin** [comment]
Party code IMHO should follow used international abbriviation of given organisation.

youth wings generally use "YP<country-code>"

**Comment by PeterTheOne** [comment]
Haven't seen it before but it could be just me.. Can you give some examples of YP being used by youth parties? Not that I have something against it. ^^

**Comment by collentine** [comment]
Agree. Same structure just replacing PP with YP.

Sweden and Norway both use the structure 'young pirate country' in their
native tongue for name

**Comment by Fafrin** [comment]
YPE - Young Pirates Europe - https://wiki.young-pirates.eu/wiki/Main_Page

**Comment by PeterTheOne** [comment]
Ok, then let's update the doc ;)

**Comment by Fafrin** [comment]
What about logo?
where and under what name should I put YPCZ or YPE logo there.

**Comment by Putr** [comment]
YPCZ seems like a good solution.

Are "young pirates" orgs. standalone organisations or are national parties their parent organisations?

As far as logo goes:
Yes the current naming policy is wrong  - it should be [partycode].[png|jpg|svg]

So just add the logo as: ypcz.png

-----------------

The existing logo files should be updated to reflect the new naming definition, as well as the docs.

The API  should be updated as well. I'll write up the issues when I have the time.

**Comment by Fafrin** [comment]
For the question of parnethood of youth wings - both is possible. YPCZ does not currently have any official conection or cooperation with PPCZ, but we would like to.

YPE is special member of PPEU. Others, i dont know.

**Comment by collentine** [comment]
In general youth organizations are independent but closely linked to their
parent organization

**Comment by PeterTheOne** [comment]
In Austria our youth organisation has no legal connect to the party, so yes both is possible.

**Comment by Fafrin** [comment]
So this:
https://github.com/Pirate-Parties-International/PPI-party-info/pull/50

Anything else?

**Comment by Fafrin** [comment]
lets close this, unless we also need to make some changes in the compiler for youth wings to show up?
