### ISSUE TITLE
PPBE missing contact info

### ISSUE THREAD

**Issue by collentine** [Pirate-Parties-International/PPI-party-info#58]
Broken link for previous contact info on PPBE http://pirateparty.be/contact-us

Couldn't find another contact from quick look at their website

**Comment by tierce** [comment]
Chnaged [here](https://github.com/Pirate-Parties-International/PPI-party-info/compare/ppat-update...tierce:patch-1)

- How to replace Google+ by our [Loomio permanent assembly](https://www.loomio.org/g/w9m0yGeJ/pirates-be-permanent-assembly) ?
- How to add our [mastodon instance and account](https://mastodon.pirateparty.be/@ppbe)
- How to add our [wiki](https://wiki.pirateparty.be/Main_Page)
- How to add our [diaspora*](http://framasphere.org/u/ppbe)

**Comment by PeterTheOne** [comment]
@tierce have a look at https://github.com/Pirate-Parties-International/PPI-party-info/blob/master/doc/data_specification.md it may answer some questions, but not all.. Feel free to add proposals to the doc.
